<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Category;
use App\Models\Association;
use App\Models\Project;
use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ProjectSeeder extends Seeder
{
    /**
     * 26 progetti strutturati e coerenti
     * Data di riferimento: 5 Giugno 2026
     * Published: expire_date > 2026-06-05
     * Completed: end_date < 2026-06-05
     */
    private function getProjects(): array
    {
        return [
            [
                'title' => 'ELF START',
                'category' => 'CES',
                'location' => 'Helsinki, Finlandia',
                'requested_people' => 4,
                'image_path' => 'img/projects/default1.png',
                'status' => 'published',
                'expire_date' => '2026-06-20',
                'start_date' => '2026-07-01',
                'end_date' => '2026-07-31',
                'sum_description' => 'Un mese immersi nella natura in Finlandia supportando l\'ecosistema locale e il lavoro forestale.',
                'full_description' => 'Vivi un\'esperienza trasformativa nel cuore delle foreste finlandesi. I volontari saranno coinvolti attivamente nella protezione della biodiversità locale, collaborando con esperti forestali per la mappatura dei sentieri naturalistici e la manutenzione delle aree protette. È l\'occasione perfetta per staccare dalla frenesia urbana e connettersi con i ritmi della natura selvaggia del Nord.',
                'requirements' => 'Età tra i 18 e i 30 anni. Non sono richieste competenze tecniche, ma una forte predisposizione al lavoro fisico all\'aperto e spirito di adattamento a condizioni climatiche variabili. Fondamentale la voglia di lavorare in un team multiculturale e il rispetto per l\'ambiente.',
                'travel_conditions' => 'Rimborso viaggio fino a 275€. Vitto e alloggio garantiti in ostello. Pocket money: 5€/giorno.',
            ],
            [
                'title' => 'OUR COMMON PATH',
                'category' => 'CES',
                'location' => 'Tampere, Finlandia',
                'requested_people' => 2,
                'image_path' => 'img/projects/default2.png',
                'status' => 'published',
                'expire_date' => '2026-06-25',
                'start_date' => '2026-07-15',
                'end_date' => '2026-08-15',
                'sum_description' => 'Volontariato di un mese per promuovere l\'inclusione sociale e l\'educazione non formale.',
                'full_description' => 'Unisciti a una missione di solidarietà urbana a Tampere. Il progetto mira a creare spazi sicuri e stimolanti per i bambini e i giovani della comunità locale attraverso laboratori artistici, giochi cooperativi e sessioni di scambio linguistico. Come volontario, sarai il motore di attività che favoriscono il dialogo tra diverse culture, lasciando un impatto tangibile sul tessuto sociale del quartiere.',
                'requirements' => 'Giovani dai 18 ai 30 anni con una spiccata propensione pedagogica. Si richiede pazienza, creatività nella gestione di gruppi di minori e una conoscenza intermedia della lingua inglese (B1) per facilitare la comunicazione con lo staff locale e gli altri partner internazionali.',
                'travel_conditions' => 'Rimborso voli fino a 275€. Alloggio in appartamento condiviso. Copertura completa per il cibo.',
            ],
            [
                'title' => 'ECO-VENTURE',
                'category' => 'CF',
                'location' => 'Skopje, Macedonia del Nord',
                'requested_people' => 15,
                'image_path' => 'img/projects/default3.png',
                'status' => 'completed',
                'expire_date' => '2026-03-20',
                'start_date' => '2026-04-16',
                'end_date' => '2026-04-23',
                'sum_description' => 'Study visit dedicata all\'ecologia e alla gestione sostenibile delle risorse giovanili.',
                'full_description' => 'Questo corso di formazione ha riunito esperti e animatori giovanili da tutta Europa per esplorare le soluzioni ecologiche nei Balcani. Attraverso visite a centri di riciclo innovativi e workshop sulla permacultura urbana, i partecipanti hanno sviluppato nuove competenze per implementare pratiche "green" nelle proprie organizzazioni di appartenenza. Un viaggio intenso tra sostenibilità e scoperta culturale.',
                'requirements' => 'Riservato a Youth Worker, educatori o project manager attivi nel terzo settore. Richiesta esperienza pregressa nella gestione di gruppi giovanili e un forte interesse professionale per l\'educazione ambientale e lo sviluppo sostenibile.',
                'travel_conditions' => 'Rimborso viaggio max 275€. Vitto e alloggio in hotel a carico dell\'organizzazione.',
            ],
            [
                'title' => 'Eco-nomy',
                'category' => 'SG',
                'location' => 'Berlino, Germania',
                'requested_people' => 20,
                'image_path' => 'img/projects/default4.png',
                'status' => 'published',
                'expire_date' => '2026-06-20',
                'start_date' => '2026-07-20',
                'end_date' => '2026-07-30',
                'sum_description' => 'Youth Exchange incentrato su economia circolare, riuso e stili di vita sostenibili in città.',
                'full_description' => 'Cosa significa vivere in modo sostenibile in una metropoli come Berlino? Questo scambio giovanile mette a confronto 20 ragazzi per ideare soluzioni pratiche al consumo di massa. Dalla visita ai mercati dell\'usato più innovativi alla creazione di piccoli business basati sull\'upcycling, i partecipanti impareranno a guardare ai rifiuti come a una risorsa, costruendo insieme un manifesto per un futuro a zero emissioni.',
                'requirements' => 'Età compresa tra i 16 e i 25 anni. Cerchiamo giovani curiosi, aperti al confronto interculturale e con una forte sensibilità verso le tematiche della sostenibilità economica e del consumo critico. Non è richiesta alcuna competenza tecnica specifica.',
                'travel_conditions' => 'Rimborso viaggio fino a 180€. Alloggio in ostello ecologico. Vitto coperto al 100%.',
            ],
            [
                'title' => 'Renovating homes',
                'category' => 'CES',
                'location' => 'Lione, Francia',
                'requested_people' => 3,
                'image_path' => 'img/projects/default5.png',
                'status' => 'completed',
                'expire_date' => '2025-08-01',
                'start_date' => '2025-09-01',
                'end_date' => '2026-03-01',
                'sum_description' => 'Sei mesi in Francia per rinnovare abitazioni di famiglie in difficoltà e fare rete.',
                'full_description' => 'Un progetto di solidarietà pura durato sei mesi. I volontari hanno affiancato artigiani locali per ristrutturare alloggi sociali, rendendoli più accoglienti ed efficienti dal punto di vista energetico. Oltre al lavoro manuale, il progetto ha previsto l\'organizzazione di momenti conviviali con i residenti, abbattendo i muri del pregiudizio e rafforzando il senso di appartenenza alla comunità locale.',
                'requirements' => 'Target 18-30 anni. Era richiesta una buona forma fisica e la disponibilità ad apprendere tecniche base di carpenteria e pittura. Fondamentale l\'empatia e la voglia di relazionarsi con contesti sociali vulnerabili.',
                'travel_conditions' => 'Rimborso viaggio 275€. Alloggio in residenza volontari. Pocket money mensile.',
            ],
            [
                'title' => 'PHOTOsyntesis',
                'category' => 'SG',
                'location' => 'Cracovia, Polonia',
                'requested_people' => 24,
                'image_path' => 'img/projects/default6.png',
                'status' => 'published',
                'expire_date' => '2026-06-15',
                'start_date' => '2026-07-05',
                'end_date' => '2026-07-15',
                'sum_description' => 'Scambio giovanile in Polonia per raccontare la natura e la società tramite la fotografia.',
                'full_description' => 'Usa l\'obiettivo per scoprire l\'anima nascosta di Cracovia. In questo scambio giovanile, la fotografia diventa un linguaggio universale per documentare il cambiamento climatico e l\'integrazione sociale. Parteciperai a safari fotografici urbani, workshop di editing e organizzerai una mostra finale aperta alla cittadinanza, imparando a narrare storie visive potenti e coinvolgenti.',
                'requirements' => 'Età 16-25 anni. È necessario possedere almeno uno smartphone con una buona fotocamera o una macchina fotografica base. Cerchiamo ragazzi creativi, appassionati di arti visive e con voglia di raccontare il mondo da prospettive diverse.',
                'travel_conditions' => 'Rimborso max 275€. Vitto e alloggio in campus universitario.',
            ],
            [
                'title' => 'GO-ON',
                'category' => 'SG',
                'location' => 'Lisbona, Portogallo',
                'requested_people' => 16,
                'image_path' => 'img/projects/default7.png',
                'status' => 'completed',
                'expire_date' => '2025-10-10',
                'start_date' => '2025-11-01',
                'end_date' => '2025-11-10',
                'sum_description' => 'Scambio giovanile sulla salute mentale e il superamento delle difficoltà post-pandemia.',
                'full_description' => 'Lisbona ha fatto da cornice a questo importante dialogo sul benessere psicologico. Attraverso sessioni di art-therapy, teatro sociale e mindfulness, i partecipanti hanno condiviso le proprie sfide emotive legate al periodo post-pandemia. Il progetto ha permesso di costruire una rete di supporto internazionale e di raccogliere strumenti pratici per gestire ansia e stress quotidiano.',
                'requirements' => 'Giovani dai 18 ai 25 anni. Si richiedeva un approccio aperto, sensibilità verso il tema della salute mentale e il massimo rispetto per le esperienze e le fragilità altrui condivise durante le attività di gruppo.',
                'travel_conditions' => 'Voli rimborsati fino a 275€. Alloggio in guest house. Pasti cucinati in gruppo.',
            ],
            [
                'title' => 'WE ARE ONE',
                'category' => 'SG',
                'location' => 'Madrid, Spagna',
                'requested_people' => 25,
                'image_path' => 'img/projects/default8.png',
                'status' => 'completed',
                'expire_date' => '2026-02-24',
                'start_date' => '2026-03-24',
                'end_date' => '2026-04-02',
                'sum_description' => 'Scambio giovanile in Spagna dedicato all\'inclusione sociale tramite lo sport di squadra.',
                'full_description' => 'Lo sport come motore di fratellanza. In questo scambio a Madrid, 25 giovani si sono messi in gioco in un torneo multiculturale dove le squadre erano composte da nazionalità miste. Tra partite di basket, calcio e sessioni di sport adattato per persone con disabilità, i partecipanti hanno abbattuto ogni barriera linguistica, scoprendo che la competizione sana è lo strumento migliore per l\'integrazione.',
                'requirements' => 'Età 16-25 anni. Non era richiesta alcuna preparazione atletica agonistica, ma dinamismo, voglia di muoversi e una forte attitudine al gioco di squadra e alla cooperazione internazionale.',
                'travel_conditions' => 'Rimborso viaggio 275€. Vitto e alloggio in ostello della gioventù.',
            ],
            [
                'title' => 'SUMMER FOR SUCCESS!',
                'category' => 'CES',
                'location' => 'Turku, Finlandia',
                'requested_people' => 4,
                'image_path' => 'img/projects/default9.png',
                'status' => 'published',
                'expire_date' => '2026-06-30',
                'start_date' => '2026-08-01',
                'end_date' => '2026-08-31',
                'sum_description' => 'Volontariato Europeo di un mese in Finlandia organizzando festival ed eventi culturali.',
                'full_description' => 'Diventa il protagonista del backstage culturale di Turku! Come volontario, sarai coinvolto nell\'organizzazione dei principali festival estivi finlandesi. Ti occuperai dell\'accoglienza degli artisti internazionali, della gestione degli spazi logistici e della creazione di contenuti social per promuovere gli eventi. Un\'esperienza adrenalinica per chi sogna di lavorare nel mondo dell\'entertainment e della cultura.',
                'requirements' => 'Giovani (18-30) carichi di energia e spirito d\'iniziativa. Sono richieste doti comunicative spiccate, capacità di gestire lo stress in ambienti dinamici e affollati e una buona conoscenza dell\'inglese parlato per interagire con il pubblico e gli artisti.',
                'travel_conditions' => 'Rimborso viaggio fino a 275€. Alloggio condiviso. Indennità mensile per il cibo e pocket money.',
            ],
            [
                'title' => 'Speak UP!',
                'category' => 'CF',
                'location' => 'Roma, Italia',
                'requested_people' => 15,
                'image_path' => 'img/projects/default10.png',
                'status' => 'published',
                'expire_date' => '2026-06-20',
                'start_date' => '2026-07-10',
                'end_date' => '2026-07-17',
                'sum_description' => 'Corso di formazione su public speaking e dibattito per leader giovanili europei.',
                'full_description' => 'Vuoi imparare a comunicare con impatto? Questo training residenziale a Roma offre una formazione intensiva sull\'arte dell\'oratoria. Utilizzando tecniche teatrali e metodologie di "Debate" internazionale, imparerai a gestire l\'ansia da palco, a strutturare argomentazioni logiche e a parlare con carisma davanti a una platea. Perfetto per chi vuole far sentire la propria voce nel sociale e nella politica.',
                'requirements' => 'Youth Worker, attivisti sociali o giovani leader di associazioni (18+). Si richiede una buona padronanza della lingua inglese (B2) e la disponibilità a mettersi in gioco in simulazioni di discorso pubblico e dibattiti accesi.',
                'travel_conditions' => 'Nessun costo di vitto e alloggio. Rimborso viaggio ricalcolato per residenti in Italia (23€-180€).',
            ],
            [
                'title' => 'Cultural Bridge',
                'category' => 'SG',
                'location' => 'Manerba del Garda, Italia',
                'requested_people' => 30,
                'image_path' => 'img/projects/default11.png',
                'status' => 'completed',
                'expire_date' => '2025-11-19',
                'start_date' => '2025-12-19',
                'end_date' => '2025-12-23',
                'sum_description' => 'Scambio breve sul Lago di Garda per costruire ponti interculturali tramite cibo e tradizioni.',
                'full_description' => 'Un incontro magico sulle rive del Garda durante il periodo natalizio. Trenta giovani hanno condiviso le tradizioni gastronomiche dei propri paesi, cucinando insieme e scoprendo come le ricette popolari raccontino storie di migrazione e fratellanza. Il progetto si è concluso con una fiera interculturale aperta alla comunità locale, tra canti, sapori e nuovi legami internazionali.',
                'requirements' => 'Target 16-25 anni. Era necessaria un\'indole socievole, curiosità verso le tradizioni culinarie altrui e voglia di collaborare nella preparazione di eventi pubblici in un contesto multiculturale festivo.',
                'travel_conditions' => 'Costi coperti integralmente. Viaggio rimborsato secondo le fasce chilometriche (Erasmus+).',
            ],
            [
                'title' => 'SUSTAINABILITY SUMMER CAMP',
                'category' => 'CES',
                'location' => 'Atene, Grecia',
                'requested_people' => 10,
                'image_path' => 'img/projects/default12.png',
                'status' => 'published',
                'expire_date' => '2026-06-18',
                'start_date' => '2026-07-15',
                'end_date' => '2026-08-15',
                'sum_description' => 'Volontariato Europeo in Grecia per ripulire le spiagge e fare divulgazione ambientale.',
                'full_description' => 'Unisciti alla battaglia per il Mediterraneo! Questo campo di volontariato ti porterà sulle coste greche per una missione ecologica: raccoglierai plastiche e rifiuti marini, ma soprattutto farai sensibilizzazione tra i turisti e i residenti. Attraverso laboratori creativi e campagne social, spiegherai l\'impatto dell\'inquinamento marino sulla fauna locale, diventando un vero ambasciatore della sostenibilità.',
                'requirements' => 'Giovani tra i 18 e i 30 anni. Si richiede una forte motivazione al lavoro manuale (anche sotto il sole), amore per il mare e buone capacità di comunicazione interpersonale per interagire con persone di diverse età e nazionalità.',
                'travel_conditions' => 'Voli rimborsati fino a 275€. Vitto e alloggio nel camp. Pocket money assicurato.',
            ],
            [
                'title' => 'Gender and Climate Edu',
                'category' => 'CF',
                'location' => 'Stoccolma, Svezia',
                'requested_people' => 20,
                'image_path' => 'img/projects/default13.png',
                'status' => 'published',
                'expire_date' => '2026-08-01',
                'start_date' => '2026-09-01',
                'end_date' => '2026-09-08',
                'sum_description' => 'Training per youth workers sull\'intersezione tra giustizia climatica e parità di genere.',
                'full_description' => 'Perché le donne sono più colpite dal cambiamento climatico? Questo training in Svezia approfondisce il legame tra giustizia sociale e ambientale. Gli operatori giovanili impareranno a integrare la prospettiva di genere nelle attività ecologiche, creando strumenti educativi che promuovano un\'azione climatica inclusiva e attenta alle vulnerabilità di tutti i membri della società.',
                'requirements' => 'Educatori, attivisti e Youth Worker (18+). È richiesta un\'ottima conoscenza della lingua inglese (C1 preferibile) e un background, anche base, sui temi del femminismo intersezionale o delle scienze ambientali.',
                'travel_conditions' => 'Voli coperti fino a 275€. Vitto e alloggio in ecovillaggio inclusi.',
            ],
            [
                'title' => 'PROJECT FRIENDSHIP',
                'category' => 'CES',
                'location' => 'Oulu, Finlandia',
                'requested_people' => 2,
                'image_path' => 'img/projects/default14.png',
                'status' => 'completed',
                'expire_date' => '2026-01-10',
                'start_date' => '2026-02-01',
                'end_date' => '2026-03-01',
                'sum_description' => 'Un mese per combattere l\'isolamento degli anziani nelle zone remote finlandesi.',
                'full_description' => 'In un inverno finlandese gelido, due volontari hanno portato calore umano nel nord del paese. Il progetto ha previsto visite quotidiane ad anziani soli, aiutandoli con le piccole commissioni ma soprattutto dedicando tempo alla conversazione e all\'insegnamento dell\'uso base dei social media per restare in contatto con i parenti lontani. Un ponte digitale e generazionale che ha commosso l\'intera comunità di Oulu.',
                'requirements' => 'Target 18-30 anni. Si richiedeva un\'eccezionale dote di empatia, pazienza e una conoscenza base degli strumenti digitali. La capacità di adattarsi a temperature molto rigide e la propensione all\'ascolto erano elementi fondamentali per il successo del progetto.',
                'travel_conditions' => 'Rimborso 360€ per il viaggio. Alloggio in famiglia. Pocket money erogato a inizio progetto.',
            ],
            [
                'title' => 'Beat the Virus',
                'category' => 'SG',
                'location' => 'Milano, Italia',
                'requested_people' => 15,
                'image_path' => 'img/projects/default15.png',
                'status' => 'completed',
                'expire_date' => '2024-03-01',
                'start_date' => '2024-04-01',
                'end_date' => '2024-04-10',
                'sum_description' => 'Scambio giovanile sulle sfide e l\'informazione ai tempi della pandemia globale.',
                'full_description' => 'Come distinguere la verità dalle fake news durante un\'emergenza sanitaria? In questo scambio a Milano, i partecipanti hanno analizzato il flusso di notizie durante il Covid-19. Attraverso dibattiti con esperti di comunicazione e medici, hanno imparato l\'importanza del fact-checking e hanno realizzato brevi video informativi per spiegare ai coetanei come proteggersi dalla disinformazione scientifica.',
                'requirements' => 'Età 16-25 anni. Era richiesto interesse per il mondo della comunicazione digitale e del giornalismo, spirito critico e voglia di analizzare l\'impatto dei media sulla società contemporanea.',
                'travel_conditions' => 'Interamente finanziato dal programma Erasmus+. Viaggio verde incoraggiato.',
            ],
            [
                'title' => 'DISCOVER FINLAND',
                'category' => 'CES',
                'location' => 'Rovaniemi, Finlandia',
                'requested_people' => 6,
                'image_path' => 'img/projects/default16.png',
                'status' => 'published',
                'expire_date' => '2026-07-15',
                'start_date' => '2026-09-01',
                'end_date' => '2027-06-01',
                'sum_description' => 'Volontariato Europeo di 9 mesi in Lapponia. Scopri la Finlandia e te stesso.',
                'full_description' => 'Nove mesi ai confini del mondo civile. Vivrai a Rovaniemi, supportando le organizzazioni giovanili locali nella gestione dei centri invernali e delle attività doposcuola per i ragazzi Sami. Avrai il compito di organizzare eventi sportivi sulla neve e workshop interculturali. È una sfida di vita che ti permetterà di sviluppare una resilienza d\'acciaio, circondato dall\'aurora boreale e da una natura mozzafiato.',
                'requirements' => 'Giovani dai 18 ai 30 anni con una maturità psicologica spiccata. È fondamentale essere pronti a vivere in un clima artico con pochissime ore di luce, dimostrando proattività, indipendenza e un forte senso di responsabilità verso i giovani beneficiari del progetto.',
                'travel_conditions' => 'Voli max 360€. Alloggio in studentato indipendente. Pocket money di 150€/mese.',
            ],
            [
                'title' => 'Fake news Wider Horizon',
                'category' => 'CF',
                'location' => 'Bruxelles, Belgio',
                'requested_people' => 25,
                'image_path' => 'img/projects/default17.png',
                'status' => 'published',
                'expire_date' => '2026-06-25',
                'start_date' => '2026-07-20',
                'end_date' => '2026-07-28',
                'sum_description' => 'Formazione per educatori su fact-checking e media literacy per contrastare la disinformazione.',
                'full_description' => 'A Bruxelles, nel cuore delle istituzioni europee, questo corso forma gli educatori a diventare sentinelle della verità digitale. Imparerai a utilizzare software di verifica delle immagini, a riconoscere i bias cognitivi e a insegnare ai giovani come navigare in modo sicuro e consapevole tra i social media. Un corso fondamentale per proteggere la democrazia nell\'era dell\'intelligenza artificiale generativa.',
                'requirements' => 'Operatori giovanili, insegnanti o attivisti digitali (18+). Si richiede un\'ottima capacità di analisi critica, dimestichezza con gli strumenti informatici e un livello fluente di inglese per seguire le lezioni tecniche e interagire con i funzionari UE.',
                'travel_conditions' => 'Rimborso viaggio max 275€. Sistemazione in hotel in camere doppie. Pasti inclusi.',
            ],
            [
                'title' => 'Education Workshop for Young',
                'category' => 'CES',
                'location' => 'Bordeaux, Francia',
                'requested_people' => 3,
                'image_path' => 'img/projects/default18.png',
                'status' => 'completed',
                'expire_date' => '2025-05-10',
                'start_date' => '2025-06-10',
                'end_date' => '2025-12-10',
                'sum_description' => 'Volontariato in Francia di 6 mesi per assistere e formare ragazzi a rischio dispersione.',
                'full_description' => 'Questo progetto ha avuto un impatto diretto sul successo scolastico di decine di giovani nelle periferie di Bordeaux. I volontari hanno creato laboratori teatrali e sportivi come strumenti per riagganciare i ragazzi che avevano abbandonato la scuola. Attraverso il tutoraggio compiti e il supporto motivazionale, i volontari sono diventati dei veri e propri modelli di riferimento positivi per i beneficiari.',
                'requirements' => 'Target 18-30 anni. Era richiesta la conoscenza base della lingua francese (A2) e una forte passione per l\'educazione alternativa. Si cercavano profili creativi, capaci di proporre attività ludiche per catturare l\'attenzione di giovani in situazioni di fragilità.',
                'travel_conditions' => 'Voli rimborsati a fine progetto (max 275€). Alloggio garantito. Rimborso per trasporti locali.',
            ],
            [
                'title' => 'Improve your Skills',
                'category' => 'CF',
                'location' => 'Vienna, Austria',
                'requested_people' => 22,
                'image_path' => 'img/projects/default19.png',
                'status' => 'completed',
                'expire_date' => '2026-01-15',
                'start_date' => '2026-02-15',
                'end_date' => '2026-02-22',
                'sum_description' => 'Migliora le tue competenze di progettazione europea e project management.',
                'full_description' => 'Un bootcamp intensivo nel cuore di Vienna per padroneggiare la burocrazia europea. I partecipanti hanno imparato a trasformare un\'idea sociale in un progetto strutturato, analizzando bandi reali e costruendo budget complessi. Il corso ha fornito le basi per gestire la rendicontazione e la comunicazione dei risultati, facilitando la creazione di nuovi partenariati tra ONG internazionali.',
                'requirements' => 'Riservato a giovani professionisti o volontari che aspirano a diventare Project Manager nel terzo settore. Si richiedeva un approccio analitico, precisione nella gestione dei dati e una conoscenza lavorativa della lingua inglese.',
                'travel_conditions' => 'Finanziato al 100%. Rimborso voli fino a 275€. Vitto e alloggio in pensione.',
            ],
            [
                'title' => 'BEE Creative. BEE Community',
                'category' => 'SG',
                'location' => 'Lubiana, Slovenia',
                'requested_people' => 20,
                'image_path' => 'img/projects/default20.png',
                'status' => 'published',
                'expire_date' => '2026-07-10',
                'start_date' => '2026-08-10',
                'end_date' => '2026-08-20',
                'sum_description' => 'Scambio sull\'importanza delle api e sulla costruzione di comunità attive e creative.',
                'full_description' => 'Scopri la Slovenia, la nazione delle api! Questo scambio giovanile unisce ecologia e arte. Imparerai i segreti dell\'apicoltura urbana e come le api siano fondamentali per la nostra sopravvivenza. I partecipanti realizzeranno "hotel per insetti" e opere d\'arte pubblica per sensibilizzare la comunità locale sulla protezione della biodiversità, il tutto vivendo in un agriturismo immerso nel verde.',
                'requirements' => 'Età 16-25 anni. Cerchiamo ragazzi amanti della natura, che non abbiano paura degli insetti e che abbiano voglia di sporcarsi le mani in attività di autocostruzione e giardinaggio creativo. Spirito di avventura e curiosità scientifica sono benvenuti.',
                'travel_conditions' => 'Viaggio rimborsato (green travel incoraggiato). Alloggio in agriturismo ecologico.',
            ],
            [
                'title' => 'Experyment Science Centre',
                'category' => 'CES',
                'location' => 'Gdynia, Polonia',
                'requested_people' => 4,
                'image_path' => 'img/projects/default21.png',
                'status' => 'completed',
                'expire_date' => '2024-11-01',
                'start_date' => '2025-01-01',
                'end_date' => '2026-01-01',
                'sum_description' => '12 mesi di volontariato presso un centro scientifico interattivo in Polonia.',
                'full_description' => 'Un anno indimenticabile come divulgatore scientifico. I volontari hanno lavorato all\'interno di uno dei centri scientifici più moderni d\'Europa, assistendo i visitatori negli esperimenti interattivi. Hanno progettato nuovi exhibit e curato i social media del centro per avvicinare i giovani alle materie STEM, dimostrando che la scienza può essere incredibilmente divertente e accessibile a tutti.',
                'requirements' => 'Target 18-30 anni. Era richiesta una curiosità innata per i fenomeni scientifici e ottime doti comunicative con il pubblico (soprattutto bambini). Si cercavano profili proattivi, capaci di lavorare in autonomia e con una buona padronanza dell\'inglese.',
                'travel_conditions' => 'Tutte le spese coperte. Alloggio in centro città. Trasporti urbani pagati dall\'hosting.',
            ],
            [
                'title' => 'Act on Stage',
                'category' => 'SG',
                'location' => 'Praga, Repubblica Ceca',
                'requested_people' => 16,
                'image_path' => 'img/projects/default22.png',
                'status' => 'published',
                'expire_date' => '2026-08-05',
                'start_date' => '2026-09-05',
                'end_date' => '2026-09-15',
                'sum_description' => 'Esprimersi tramite il teatro dell\'oppresso e l\'arte drammatica davanti alla videocamera.',
                'full_description' => 'Le luci di Praga ti aspettano! In questo scambio giovanile, utilizzerai il teatro come strumento per denunciare le ingiustizie sociali. Parteciperai a workshop di recitazione cinematografica e imparerai a scrivere sceneggiature brevi. Il progetto culminerà nella produzione di tre cortometraggi amatoriali che verranno caricati su una piattaforma europea dedicata al cambiamento sociale tramite l\'arte.',
                'requirements' => 'Età 16-25 anni. Cerchiamo giovani con la passione per la recitazione, la regia o la scrittura creativa. Non è richiesta esperienza professionale, ma tanta voglia di esporsi, mettersi in gioco davanti alla telecamera e lavorare intensamente in gruppo.',
                'travel_conditions' => 'Rimborso viaggio max 275€. Vitto e alloggio inclusi in struttura giovanile.',
            ],
            [
                'title' => 'INTERCULTURAL EXCHANGE',
                'category' => 'CES',
                'location' => 'Marsiglia, Francia',
                'requested_people' => 3,
                'image_path' => 'img/projects/default23.png',
                'status' => 'published',
                'expire_date' => '2026-08-20',
                'start_date' => '2026-09-20',
                'end_date' => '2027-07-20',
                'sum_description' => 'Volontariato Europeo di 10 mesi a Marsiglia basato sull\'educazione non formale.',
                'full_description' => 'Marsiglia è un crocevia di popoli e tu sarai nel centro di questo fermento. Collaborerai con un centro sociale multiculturale, organizzando laboratori per giovani immigrati di seconda generazione. Dallo sport allo studio assistito, fino alla gestione di una web radio comunitaria, il tuo compito sarà quello di favorire l\'integrazione e dare voce a chi spesso non viene ascoltato nelle periferie urbane.',
                'requirements' => 'Giovani dai 18 ai 30 anni. Si richiede una mentalità aperta, assenza di pregiudizi e una buona dose di autonomia. È preferibile una conoscenza base del francese (A1/A2), ma soprattutto una grande motivazione a lavorare in contesti sociali complessi e stimolanti.',
                'travel_conditions' => 'Voli, vitto e alloggio coperti (stanza singola in appartamento condiviso). Pocket money di 180€ mensili.',
            ],
            [
                'title' => 'Digital Youth Lab',
                'category' => 'CF',
                'location' => 'Tallinn, Estonia',
                'requested_people' => 20,
                'image_path' => 'img/projects/default24.png',
                'status' => 'completed',
                'expire_date' => '2026-03-01',
                'start_date' => '2026-04-01',
                'end_date' => '2026-04-08',
                'sum_description' => 'Digitalizzazione del youth work: usa la tecnologia per raggiungere più giovani.',
                'full_description' => 'Tallinn, la capitale digitale d\'Europa, ha ospitato questa formazione d\'avanguardia. Gli operatori giovanili hanno esplorato come l\'intelligenza artificiale e le piattaforme di gamification possano rendere le attività sociali più attraenti per la "Generazione Z". Il corso ha fornito competenze su come gestire comunità online sicure e come utilizzare i dati per misurare l\'impatto sociale dei propri progetti.',
                'requirements' => 'Riservato ad animatori giovanili ed educatori con una buona base tecnologica. Si richiedeva apertura verso le nuove tecnologie e la volontà di digitalizzare i processi educativi delle proprie associazioni di provenienza.',
                'travel_conditions' => 'Rimborso max 275€. Pernottamento in business hotel. Pasti completi.',
            ],
            [
                'title' => 'Power Abuse',
                'category' => 'CF',
                'location' => 'Barcellona, Spagna',
                'requested_people' => 25,
                'image_path' => 'img/projects/default25.png',
                'status' => 'published',
                'expire_date' => '2026-06-15',
                'start_date' => '2026-07-10',
                'end_date' => '2026-07-17',
                'sum_description' => 'Corso di formazione su leadership etica e prevenzione degli abusi di potere.',
                'full_description' => 'Un tema delicato e fondamentale per chi gestisce gruppi. Questo corso a Barcellona analizza le dinamiche di potere all\'interno delle organizzazioni non profit. Imparerai a riconoscere i segnali di abuso psicologico, a promuovere una leadership orizzontale e a creare protocolli di sicurezza per i volontari e i beneficiari. Un percorso di crescita professionale per rendere il terzo settore un luogo sempre più sicuro e trasparente.',
                'requirements' => 'Dirigenti di ONG, coordinatori di volontariato o Youth Worker esperti (18+). Si richiede maturità personale, predisposizione all\'autocritica e un livello avanzato di inglese per partecipare attivamente a sessioni di analisi psicologica e strutturale.',
                'travel_conditions' => 'Spese rimborsate fino a 275€. Sistemazione in campus. Colazione e cena incluse.',
            ],
            [
                'title' => 'Critical Thinkers',
                'category' => 'SG',
                'location' => 'Sofia, Bulgaria',
                'requested_people' => 30,
                'image_path' => 'img/projects/default26.jpg',
                'status' => 'published',
                'expire_date' => '2026-07-01',
                'start_date' => '2026-08-01',
                'end_date' => '2026-08-10',
                'sum_description' => 'Youth Exchange per sviluppare il pensiero critico in un\'era di sovraccarico informativo.',
                'full_description' => 'Non farti manipolare dai social! Questo scambio a Sofia ti insegnerà a smontare le tesi fallaci e a riconoscere le tecniche di propaganda online. Attraverso intensi dibattiti in stile Oxford e giochi di ruolo sulla manipolazione dell\'informazione, imparerai a difendere le tue idee con logica e pacatezza, diventando un cittadino digitale consapevole e capace di influenzare positivamente i tuoi coetanei.',
                'requirements' => 'Età 16-25 anni. Cerchiamo ragazzi appassionati di attualità, che amano discutere e che vogliono migliorare le proprie capacità logiche e dialettiche. È richiesta una conoscenza base della lingua inglese e molta voglia di confrontarsi con opinioni diverse dalla propria.',
                'travel_conditions' => 'Viaggio rimborsato entro massimali Erasmus+ (275€). Alloggio in guest house.',
            ],
        ];
    }

    public function run(): void
    {
        $admin = User::where('role', 'admin')->first();
        if (!$admin) {
            $admin = User::factory()->create(['role' => 'admin', 'name' => 'Admin Principale', 'email' => 'admin.progetti@atelier.it']);
        }

        $cats = Category::all()->keyBy('tag');
        $assoc = Association::all();

        // Mappa categoria da string a ID
        $categoryMap = [
            'CES' => $cats->get('ESC')?->id,
            'SG' => $cats->get('YTH')?->id,
            'CF' => $cats->get('TRG')?->id,
        ];

        // Cicla attraverso i progetti e creali
        foreach ($this->getProjects() as $projectData) {
            $categoryId = $categoryMap[$projectData['category']] ?? null;
            $associationId = $assoc->isNotEmpty() ? $assoc->random()->id : null;

            // Crea progetto se non esiste già
            Project::firstOrCreate(
                ['title' => $projectData['title']],
                [
                    'user_id' => $admin->id,
                    'category_id' => $categoryId,
                    'association_id' => $associationId,
                    'location' => $projectData['location'],
                    'requested_people' => $projectData['requested_people'],
                    'image_path' => $projectData['image_path'],
                    'status' => $projectData['status'],
                    'expire_date' => Carbon::parse($projectData['expire_date']),
                    'start_date' => Carbon::parse($projectData['start_date']),
                    'end_date' => Carbon::parse($projectData['end_date']),
                    'sum_description' => $projectData['sum_description'],
                    'full_description' => $projectData['full_description'],
                    'requirements' => $projectData['requirements'],
                    'travel_conditions' => $projectData['travel_conditions'],
                ]
            );
        }

        $this->command->info('✓ Creati/Aggiornati 26 progetti strutturati e coerenti');
        $this->command->info('  - Pubblicati: ' . Project::where('status', 'published')->count());
        $this->command->info('  - Completati: ' . Project::where('status', 'completed')->count());
    }
}
